project_id = "vnqqkrrlaalyezslpevg"

[functions.bulk-upload-students]
verify_jwt = true

[functions.validate-teacher-token]
verify_jwt = false

[functions.submit-scores]
verify_jwt = false

[functions.validate-result-pin]
verify_jwt = false